<?php
// Variables
return [
  "creatorName" => "EC",
  "creatorUrl" => "EC",
  "templateName" => "CloudiMesh",
  "templateSuffix" => " - ",
  "templateVersion" => "1.0.0",
  "templateFree" => false,
  "templateDescription" => "",
  "templateKeyword" => "",
  "licenseUrl" => "",
  "livePreview" => "",
  "productPage" => "",
  "support" => "",
  "moreThemes" => "",
  "documentation" => "",
  "generator" => "",
  "changelog" => "",
  "repository" => "",
  "gitRepo" => "",
  "gitRepoAccess" => "",
  "githubFreeUrl" => "",
  "facebookUrl" => "",
  "twitterUrl" => "",
  "githubUrl" => "",
  "dribbbleUrl" => "",
  "instagramUrl" => "",
];
